# Run file to install dependencies
install.packages("shiny", dependencies = TRUE)
install.packages("imager", dependencies = TRUE)
install.packages("MASS", dependencies = TRUE)
install.packages("dequer", dependencies = TRUE)
install.packages("magick", dependencies = TRUE)
install.packages("tesseract", dependencies = TRUE)
install.packages("DT", dependencies = TRUE)
install.packages("hunspell", dependencies = TRUE)
install.packages("ggplot2", dependencies = TRUE)
install.packages("tidyverse", dependencies = TRUE)
